### ISSUE TITLE
妖怪之山角色互动——河童，程序部分

### ISSUE THREAD

**Issue by AMXELCbis** [AMXELCbis/Touhou-Ball#27]
任务简介：制作妖怪之山赛道的角色互动之一，河童。该角色互动为放置在平面上的，会玩家打滑的赛道，可位于其他基础平面上。

程序要求描述：
1，不需要制作任何模型，只需要hitbox来触发
2，制作触发hitbox后使玩家打滑的脚本
  a) 在触发后玩家会打滑，玩家离开该区域后效果结束
  b) hitbox的大小需要可以控制
  c) 玩家打滑的摩擦系数也需要可以控制
  d) hitbox不应该是覆盖整个空间的立方体，玩家**离开赛道表面，但依然处于hitbox空间时**，不应该收到打滑影响

**Comment by AMXELCbis** [comment]
补充：
![image](https://github.com/AMXELCbis/Touhou-Ball/assets/90291638/946777be-a4bd-4e8d-bf6f-35437a7efb3c)

不考虑模拟在光滑平面上加速度变化的问题，即如果文文和河童同时在一个区域，只需要过各自的算法即可，彼此没有进一步的交互，互不影响

**Comment by AMXELCbis** [comment]
在nitro区域时，小球虽然会比较难操控（“打滑”），但松开控制后小球会保持速度匀速移动，而不是慢慢停下。要求是模拟地面打滑的效果，但即使是光滑的地面小球也是会慢慢停下**（但是要比在普通地面要慢些）**

**Comment by sousya** [comment]
可以通过调节Nitori脚本SlipperyPower参数修改达到效果（SlipperyPower等价于角色身上rigidbody的drag参数）
