### ISSUE TITLE
重生系统的重生位置及重置速度

### ISSUE THREAD

**Issue by AMXELCbis** [AMXELCbis/Touhou-Ball#34]
任务要求：玩家死亡重生回检查点时，需要平稳的在平面重生，同时速度为0

设计要求：不能强行调整检查点在地图位置来达到效果，检查点方块同时也需要紧贴地面而不穿模

补充：我看了重生的代码，似乎速度是会被重置为0的。目前小球重置后还有速度好像就是因为重生的位置是空中

**Comment by AMXELCbis** [comment]
暂时不确定具体诱发条件

描述：在TilemapTest里，位于水平面的两个重生点都能正常使用，但上到左边高处平台的重生点后，玩家不会在重生点复活，并且动不了（控制不了，因为重生在赛道里面了）

**Comment by sousya** [comment]
场景地面gameobject需要将layer设置成ground
