### ISSUE TITLE
制作玩家剩余生命数的素材

### ISSUE THREAD

**Issue by AMXELCbis** [AMXELCbis/Touhou-Ball#45]
要求：制作用于显示玩家剩余生命数的HUD素材

描述：自由发挥，根据主角来设计素材，制作好的素材在unity自建文件夹存放

想法和参考：因为主角是小碗，所以该素材可以是Q版的小碗大头像，或者是单纯的一个碗（小碗的碗）也可以，具体怎么设计自由发挥。若是想进阶一点，可以绘制多种不同命数下，有区别的素材

**Comment by zeew001** [comment]
file uploaded
