### ISSUE TITLE
制作HUD数字翻转的效果

### ISSUE THREAD

**Issue by AMXELCbis** [AMXELCbis/Touhou-Ball#69]
制作HUD数字翻转的效果，类似于FF16的结算画面的数字

该效果会用于：
1，HUD命数。用于显示玩家剩余命数。比如一开始有三条命，每死一次减一条命：数字变化为3→2→1这样
2，HUD计时器。计时器。可能会用于倒计时或者计时。数字变化可能为60→59→...这样
3，其他直接显示数字的HUD/UI。直接显示一个数字。数字变化为 null→100（具体数字）

要求：
1，支持连续的数字变换。比如 2→50→200→10这样
2，根据加减的情况来决定翻转方向

**理想output**：
一个prefab，script可输入参数包含：
1，目标数字（初始可为0，具体显不显示初始数看你）。只要我更改了目标数字，翻转效果就会开始，从老数字变换到新数字
2，变化时间。一次变化所需的时间
3，其他你觉得需要的或者是可选目标的内容

**制作上可能遇到的问题：**
1，不用考虑负数或者小数
2，关于初始状态：可以以没有数字开始，或者直接以数字0开始，两个都行。（可选）把两种情况都做出来，加一个toggle支持选择哪种模式
3，数字不会特别大，应该不会超过6、7位数

**Comment by AMXELCbis** [comment]
![image](https://github.com/AMXELCbis/Touhou-Ball/assets/90291638/d993d52e-e3c0-4519-808d-88be26f4303e)
补充

**Comment by sousya** [comment]
主要脚本 TimerText
beginPos 控制字符结束位置（控制y轴用）
totalTime 控制滚动总时长（useTotalTime == true时生效）
rollTime 每格滚动一次时间（useTotalTime == false时生效）

使用方法 设定初始值 SetBeginNum(初始数值) 然后StartRoll(目标数值)

至于补充的问题 我的理解是直接调整组件的scale就能放大了 不知道你是还有什么别的需求
